import { getData } from "./cache.mjs";

const dataContainer = document.querySelector(".pokemon-data");

/** @param {string} name  */
export async function updatePokemonData(name) {
  const url = `https://pokeapi.co/api/v2/pokemon/${name}`;
  const data = await getData(url);
  const html = dataTemplate(data);
  dataContainer.innerHTML = '';
  dataContainer.insertAdjacentHTML('beforeend', html);
}

/** @param {Pokemon} pokemon */
const dataTemplate = (pokemon) => {
  return `
  <h2>${pokemon.name}</h2>
  <img src="${pokemon.sprites.front_default}" alt="sprite of ${pokemon.name}" />
  <br>
  <button onclick="new Audio('${pokemon.cries.latest ?? pokemon.cries.legacy}').play()">Sound</button>
  `;
};

// Pokemon JSDoc generated by ChatGPT

/**
 * @typedef {Object} PokemonAbility
 * @property {Object} ability
 * @property {string} ability.name - The name of the ability.
 * @property {string} ability.url - The URL to the ability's API endpoint.
 * @property {boolean} is_hidden - Whether the ability is hidden.
 * @property {number} slot - The slot position of the ability.
 */

/**
 * @typedef {Object} PokemonMoveLearnMethod
 * @property {string} name - The move learn method (e.g., "level-up", "machine").
 * @property {string} url - The URL to the move learn method API endpoint.
 */

/**
 * @typedef {Object} PokemonVersionGroup
 * @property {string} name - The version group name (e.g., "scarlet-violet").
 * @property {string} url - The URL to the version group API endpoint.
 */

/**
 * @typedef {Object} PokemonMoveVersionDetail
 * @property {number} level_learned_at - The level at which the move is learned.
 * @property {PokemonMoveLearnMethod} move_learn_method - Method by which the move is learned.
 * @property {number|null} order - The order of the move learning, if applicable.
 * @property {PokemonVersionGroup} version_group - The version group for the move.
 */

/**
 * @typedef {Object} PokemonMove
 * @property {Object} move
 * @property {string} move.name - The name of the move.
 * @property {string} move.url - The URL to the move API endpoint.
 * @property {PokemonMoveVersionDetail[]} version_group_details - Details per game version.
 */

/**
 * @typedef {Object} PokemonForm
 * @property {string} name - Form name.
 * @property {string} url - URL to form API endpoint.
 */

/**
 * @typedef {Object} PokemonSpecies
 * @property {string} name - Species name.
 * @property {string} url - URL to species API endpoint.
 */

/**
 * @typedef {Object} PokemonStat
 * @property {number} base_stat - Base stat value.
 * @property {number} effort - Effort value (EV) yield.
 * @property {Object} stat
 * @property {string} stat.name - Stat name (e.g., "hp", "attack").
 * @property {string} stat.url - URL to stat API endpoint.
 */

/**
 * @typedef {Object} PokemonType
 * @property {number} slot - The slot order of the type.
 * @property {Object} type
 * @property {string} type.name - Type name (e.g., "fighting").
 * @property {string} type.url - URL to type API endpoint.
 */

/**
 * @typedef {Object} PokemonSpriteSet
 * @property {string|null} back_default
 * @property {string|null} back_female
 * @property {string|null} back_shiny
 * @property {string|null} back_shiny_female
 * @property {string|null} front_default
 * @property {string|null} front_female
 * @property {string|null} front_shiny
 * @property {string|null} front_shiny_female
 */

/**
 * @typedef {Object} PokemonSprites
 * @property {PokemonSpriteSet} [other.dream_world]
 * @property {PokemonSpriteSet} [other.home]
 * @property {PokemonSpriteSet} [other.official-artwork]
 * @property {PokemonSpriteSet} [other.showdown]
 * @property {Object} versions - Sprites per game version (nested objects similar to above)
 * @property {PokemonSpriteSet} [generation-i.red-blue]
 * @property {PokemonSpriteSet} [generation-i.yellow]
 * @property {PokemonSpriteSet} [generation-ii.crystal]
 * @property {PokemonSpriteSet} [generation-ii.gold]
 * @property {PokemonSpriteSet} [generation-ii.silver]
 * @property {PokemonSpriteSet} [generation-iii.emerald]
 * @property {PokemonSpriteSet} [generation-iii.firered-leafgreen]
 * @property {PokemonSpriteSet} [generation-iii.ruby-sapphire]
 * @property {PokemonSpriteSet} [generation-iv.diamond-pearl]
 * @property {PokemonSpriteSet} [generation-iv.heartgold-soulsilver]
 * @property {PokemonSpriteSet} [generation-iv.platinum]
 * @property {PokemonSpriteSet} [generation-v.black-white]
 * @property {PokemonSpriteSet} [generation-vi.omegaruby-alphasapphire]
 * @property {PokemonSpriteSet} [generation-vi.x-y]
 * @property {PokemonSpriteSet} [generation-vii.icons]
 * @property {PokemonSpriteSet} [generation-vii.ultra-sun-ultra-moon]
 * @property {PokemonSpriteSet} [generation-viii.brilliant-diamond-shining-pearl]
 * @property {PokemonSpriteSet} [generation-viii.icons]
 * @property {PokemonSpriteSet} [generation-ix.scarlet-violet]
 */

/**
 * @typedef {Object} Pokemon
 * @property {number} id - Unique Pokémon ID.
 * @property {string} name - Pokémon name.
 * @property {number} base_experience - Base experience yield.
 * @property {number} height - Height in decimetres.
 * @property {number} weight - Weight in hectograms.
 * @property {PokemonAbility[]} abilities - List of abilities.
 * @property {PokemonMove[]} moves - List of moves.
 * @property {PokemonForm[]} forms - Available forms.
 * @property {string} location_area_encounters - URL to location encounters.
 * @property {boolean} is_default - Whether this is the default form.
 * @property {PokemonSpecies} species - Species information.
 * @property {PokemonSprites} sprites - Sprite URLs.
 * @property {PokemonStat[]} stats - List of stats.
 * @property {PokemonType[]} types - Pokémon types.
 * @property {Object} cries - Audio URLs
 * @property {string} cries.latest - URL for latest cry.
 * @property {string|null} cries.legacy - URL for legacy cry.
 * @property {Object[]} held_items - Held items (if any)
 * @property {Object[]} past_abilities - Past abilities (if any)
 * @property {Object[]} past_types - Past types (if any)
 * @property {number} order - Internal order used for sorting.
 */
